### ISSUE TITLE
Unclear doc: Uploading an extension to pootle 

### ISSUE THREAD

**Issue by boite** [1drop/pootle#7]
I'm having difficulty understanding how to get files to be maintained by the pootle server.  The README gives two options, the first being:-

In order to get the files there you can either add a SFTP container that has access to a specific repo folder e.g.

    sftp:
      image: atmoz/sftp
      volumes:
        - /host/share:/home/foo/share
      ports:
        - "2222:22"
      command: foo:123:1001

---

I tried adding something like the example to `docker-compose.yml`:-

    version: '2'
    
    services: 
      ...
      sftp:
        image: atmoz/sftp
        volumes:
          - /path/to/my.repo:/srv/pootle/git-clones/repos/my.repo
        ports:
          - "2222:22"
        command: repowner:123:1001
    
    volumes:
      mysql-data:
      l10n-ter:
      pootle-po:
      pootle-git:
    
but this doesn't get the files into pootle:-

    $ docker-compose exec pootle bash -c "ls -al /srv/pootle/git-clones"
    total 8
    drwxr-xr-x 2 root root 4096 Aug 18 14:53 .
    drwxr-xr-x 4 root root 4096 Aug 21 11:39 ..
    $

What am I missing?

**Comment by arky** [comment]
Perhaps you need to 'pootle update_stores' ?
http://docs.translatehouse.org/projects/pootle/en/stable-2.7.2/server/commands.html#django-admin-update_stores

**Comment by htuscher** [comment]
Regarding the docker-compose.yml if you would like to push a repo to your pootle instance via SFTP you would do e.g. this:

```
services:
pootle:
    image: 1drop/pootle:pootle
    volumes:
      - /path/to/my.repo:/srv/pootle/git-clones/my.repo
      - /path/to/another.repo:/srv/pootle/git-clones/another.repo
  sftp:
    image: atmoz/sftp
    command: foo:pass:1001
    volumes:
      - /path/to/my.repo:/home/foo/upload
  sftpanother:
    image: atmoz/sftp
    command: foo:pass:1001
    volumes:
      - /path/to/another.repo:/home/foo/upload
```
